### ISSUE TITLE
in evaluation, report inbreeding coef and additive relationships between submitted genotypes

### ISSUE THREAD

**Issue by timflutre** [timflutre/PlantBreedGame#14]
One can do it using the pedigree of each breeder separately as well as the whole pedigree (c.f. package [kinship2](https://cran.r-project.org/package=kinship2)). Idem using the markers (via `estimGenRel` of the package `rutilstimflutre`).

**Comment by juliendiot42** [comment]
I added a new tab in evaluation: "additive relationships"
You can choose a breeder and the matrix return by the `estimGenRel` function is shown for the submitted individuals this breeder.

My skills in genetic are quite limited, so I don't know if the whole matrix is interesting as the comparison between individuals from all breeders together.

**Comment by timflutre** [comment]
Close because it's good enough for the moment!
