### ISSUE TITLE
[improvment] symbolic links for "admin" and "test" are absolute, but relative for other breeders.

### ISSUE THREAD

**Issue by juliendiot42** [timflutre/PlantBreedGame#28]
It might be better to use relative path for all so that one can duplicate a game session on another computer without troubles. 

For "admin": 
![image](https://user-images.githubusercontent.com/34234917/154383522-dacc7db5-1e44-4b3f-9273-9d044459d30b.png)

For another breeder:
![image](https://user-images.githubusercontent.com/34234917/154383577-141227a8-3f82-4c92-8e30-25ebe4a8c424.png)

**Comment by timflutre** [comment]
Yes, that's a good idea!
