### ISSUE TITLE
Possible time difference between user and game server

### ISSUE THREAD

**Issue by juliendiot42** [timflutre/PlantBreedGame#35]
The session management in the game is made using the **server's time**, not the user's time. If there is a time difference between both, the sessions will not start at the expected (user) time.

For example for a session with parameters:
  - Start: `2024-06-21 00:01:00`
  - End: `2024-06-21 23:59:00`
  - Year duration: 365 (1min IRL = 1 Game day)
 
 At 09h18 JST (0h18 UTC) the game could show "18 Jan 2015" (18 days have passed) if the server use UTC time. But such Japanese user would expect ~ "July 12, 2016" (01 Jan 2015 + (60*9 + 18) days).
 
 
 
 ### Possible "fix"
 
1. "Work-around" (very easy to implement): Show a warning that mention the game session start and end date should consider the game servers's time. (And possibly show the time-zone of the server, to help the user). The user then have to do the conversion.
2. For a better fix, something easy to implement can be to ask the time-zone of the game session's start/end times.  Then the game take that in account for calculating the game time.
3. More complex (and maybe more bug prone solution) detect automatically the time-zone of the user and consider it as for the solution 2.

**Comment by timflutre** [comment]
I think it is better to start by implementing option 2. Can you do it?

**Comment by juliendiot42** [comment]
Sure !

**Comment by juliendiot42** [comment]
This is fixed with 1d3592002ec7310bc0aabf7b9251d4bf95c7526c

I have implemented a mix between option 2 and 3.

Now there is a new parameter for creating sessions: "Time zone", so the user can specify its time zone and the server will take it in consideration when calculating the game time.

![image](https://github.com/timflutre/PlantBreedGame/assets/34234917/777f1197-f0b3-4fd6-b057-3cb09a1d60a6)


By default this "Time zone" will have value "UTC", however, the app will get the the time zone of the user's browser and set this value automatically. I preferred to do that rather than doing it 100% automatically (option 3) so the user still have control on this.

Some additional improvement have also been made:

The "Session table" is more complete and have information about the start/end/duration of the session in "Game time":

![image](https://github.com/timflutre/PlantBreedGame/assets/34234917/84c73dfe-787b-44d8-b0e6-be00d10af2e5)

And the game time calculation function is tested with unit tests.

**Comment by timflutre** [comment]
Great!
