### ISSUE TITLE
Maximum number of individuals registered not enforced

### ISSUE THREAD

**Issue by chabrault** [timflutre/PlantBreedGame#41]
In the Admin / Game initialisation / Other, we can modify the final evaluation registration, the default is 4 and I changed it to 2.

- I was still able to select 5 individuals for the final registration

- The text wasn't updated with the parameter value in **Register final individuals** and in **How to play / Final trial**.

By the way, I tried registering individuals from the test request "pltMat_init_set100.txt", which are allofecundations from the initial set (F1) and it worked. Does this mean that the heterozygosity criterion is not checked?

**Comment by juliendiot42** [comment]
Hello,

> we can modify the final evaluation registration, the default is 4 and I changed it to 2.

This parameter is the cost of the registration, not the maximum number of individuals players can register.
(This is under the " Costs and budget" section. (But it happens that it was not updated neither, I'll fix it.)

The maximum number of individual to register can not be defined currently. I'll will implement it.

> By the way, I tried registering individuals from the test request "pltMat_init_set100.txt", which are allofecundations from the initial set (F1) and it worked. Does this mean that the heterozygosity criterion is not checked?

Indeed now there is no check on the registered individuals, and there is no information about their heterozygosity in the evaluation results. 
I am not sure about implementing a feature that prevent such heterozygotes individuals to be registered as such rule may be too strict for some players. But being able to check this in the evaluation result is good (then each players can take this information into account as they wish).

**Comment by juliendiot42** [comment]
Now you can select the maximum number of registered individuals in the game initialisation menu under "Game requests constraints".
