### ISSUE TITLE
Enhancement: recapitulate all operations duration and cost in one table

### ISSUE THREAD

**Issue by chabrault** [timflutre/PlantBreedGame#48]
After playing the game, I had the request of adding a table which recapitulates all the costs and duration of the operations.
I did one for presenting to the players, you could take that as an example an integrate it to the game.

![image](https://github.com/user-attachments/assets/d6420623-0f82-4eca-b89d-187d19558d1d)

**Comment by timflutre** [comment]
Nice!

**Comment by juliendiot42** [comment]
@chabrault 
This can be nice indeed, however, I don't really know where I could put this table. Would you have any suggestion ?

(By the way, I can make a new menu. Only for that would be too much inho but if there is other kind of similar information, why not)

**Comment by chabrault** [comment]
@juliendiot42 you could put that under the "Experimental and financial means" in the "How to play" tab.

**Comment by juliendiot42** [comment]
Indeed ! Thank !

**Comment by juliendiot42** [comment]
@chabrault 

This is how it looks like:

![image](https://github.com/user-attachments/assets/387edc3d-92a1-478b-97ff-e01fd42384eb)

It is rather simple but it is already usable and an still an improvement so I have pushed to master. However I can still beautify it if you want ^^
