### ISSUE TITLE
commit "data" folder to be able to use "shiny::runGitHub"

### ISSUE THREAD

**Issue by juliendiot42** [timflutre/PlantBreedGame#7]
It could be good to include the "data" folder in the repo of the app so that anyone can lunch the app just by using:
``shiny::runGitHub("timflutre/PlantSelBreedGame")``

**Comment by timflutre** [comment]
The current `data` directory contains many binary files (not optimal for git), and is quite big (not optimal for GitHub). But this could be a future improvement.
