### ISSUE TITLE
convert the app into a proper R package

### ISSUE THREAD

**Issue by timflutre** [timflutre/PlantBreedGame#8]
Not sure if it's a good idea in our case, but here is some info:

https://www.mango-solutions.com/blog/packaging-shiny-applications-a-deep-dive

**Comment by timflutre** [comment]
Having a proper R package would also clarify the package imports, and would allow testing via `R CMD check` (see [here](http://r-pkgs.had.co.nz/tests.html)).

**Comment by juliendiot42** [comment]
Since it is packaged with Nix I don't think it is necessary any more.
